"""
Inference-time predictor: loads the trained model once (lazily, on first
use) and exposes a single `predict()` call that returns everything the
prediction page and PDF report need — top-k predictions, a Grad-CAM
heatmap, risk level, and timing.
"""
from __future__ import annotations

import base64
import json
import os
import time
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Optional

import cv2
import numpy as np

from preprocessing.preprocess import preprocess_image
from utils.file_utils import load_class_names
from utils.logger import get_logger

logger = get_logger(__name__)

# Simple, documented mapping from predicted class -> qualitative risk
# level. "Healthy" is the only class treated as low risk; every disease
# class defaults to at least moderate risk, escalated by confidence.
_LOW_RISK_CLASSES = {"healthy", "normal"}


@dataclass
class PredictionResult:
    predicted_class: str
    confidence: float
    top_k: List[Dict[str, float]]
    all_probabilities: Dict[str, float]
    risk_level: str
    explanation: str
    inference_time_ms: float
    model_version: str
    architecture: str
    timestamp: str
    gradcam_base64: Optional[str] = None
    disclaimer: str = (
        "This prediction is generated by an AI research model and is NOT "
        "a medical diagnosis. Always consult a qualified ophthalmologist "
        "or medical professional for clinical decisions."
    )
    errors: List[str] = field(default_factory=list)

    @property
    def is_valid(self) -> bool:
        return not self.errors


class Predictor:
    """Lazily-loaded singleton-style wrapper around the trained Keras
    model. Instantiate once (e.g. in the Flask app factory / service
    layer) and reuse across requests."""

    def __init__(self, config) -> None:
        self.config = config
        self._model = None
        self._class_names: List[str] = []
        self._version_info: Dict = {}
        self._last_conv_layer_name = config.GRADCAM_LAST_CONV_LAYER

    # ------------------------------------------------------------------
    @property
    def is_loaded(self) -> bool:
        return self._model is not None

    @property
    def class_names(self) -> List[str]:
        return list(self._class_names)

    @property
    def version_info(self) -> Dict:
        return dict(self._version_info)

    def _model_path(self) -> Optional[str]:
        candidates = [
            os.path.join(
                self.config.SAVED_MODELS_DIR,
                f"{self.config.MODEL_NAME}_best.keras",
            ),
            os.path.join(
                self.config.SAVED_MODELS_DIR,
                f"{self.config.MODEL_NAME}_final.keras",
            ),
        ]
        for path in candidates:
            if os.path.isfile(path):
                return path
        return None

    def load(self) -> bool:
        """Load the trained model and its metadata from disk. Returns
        False (without raising) if no trained model is available yet, or
        if TensorFlow is not installed — the Flask app should stay up and
        report this via /health rather than crash on startup, since a
        fresh clone won't have a model until the user trains one."""
        model_path = self._model_path()
        if model_path is None:
            logger.warning(
                "No trained model found in '%s'. Train one with "
                "`python train.py` or place a Kaggle-trained checkpoint "
                "there.",
                self.config.SAVED_MODELS_DIR,
            )
            return False

        try:
            import tensorflow as tf  # local import: keep TF off the Flask
            # import path until a prediction is actually requested, so
            # route registration and non-ML pages don't require TF
            # to be installed.
        except ImportError:
            logger.error(
                "TensorFlow is not installed. Install the dependencies "
                "in requirements.txt to enable predictions."
            )
            return False

        self._model = tf.keras.models.load_model(model_path)
        self._class_names = load_class_names(
            self.config.SAVED_MODELS_DIR, self.config.DATASET_DIR
        )

        version_path = os.path.join(
            self.config.SAVED_MODELS_DIR, "model_version.json"
        )
        if os.path.isfile(version_path):
            with open(version_path, "r", encoding="utf-8") as fh:
                self._version_info = json.load(fh)

        logger.info(
            "Loaded model from '%s' with %d classes.",
            model_path,
            len(self._class_names),
        )
        return True

    # ------------------------------------------------------------------
    def _risk_level(self, predicted_class: str, confidence: float) -> str:
        normalized = predicted_class.strip().lower().replace(" ", "_")
        if normalized in _LOW_RISK_CLASSES:
            return "Low"
        if confidence >= 0.75:
            return "High"
        if confidence >= 0.45:
            return "Moderate"
        return "Low-Moderate (low model confidence)"

    def _explanation(self, predicted_class: str, risk_level: str) -> str:
        normalized = predicted_class.strip().lower().replace(" ", "_")
        if normalized in _LOW_RISK_CLASSES:
            return (
                "No signs consistent with the trained disease classes "
                "were detected in this fundus image."
            )
        return (
            f"The model detected visual patterns consistent with "
            f"'{predicted_class.replace('_', ' ')}'. Risk level is "
            f"assessed as {risk_level} based on model confidence. This "
            "is a screening aid only, not a clinical diagnosis."
        )

    def _generate_gradcam(
        self, preprocessed_image: np.ndarray, class_index: int
    ) -> Optional[str]:
        """Generate a Grad-CAM heatmap overlay for the predicted class and
        return it as a base64-encoded PNG data string for direct embedding
        in the result page / PDF report.

        Implementation note: the backbone (EfficientNet/DenseNet/ResNet)
        is nested inside the outer model as a single sub-model layer.
        Keras cannot directly wire an *intermediate* tensor from inside a
        nested sub-model into a new `Model` built against the *outer*
        model's input — the sub-model is an opaque boundary. Instead we:
          1. Build a small model from the backbone's own input to its
             target conv layer AND its own final output (both tensors
             live in the backbone's own graph, so this wiring is valid).
          2. Manually replay the outer model's head layers (GAP -> BN ->
             Dropout -> Dense -> ... -> softmax) on the backbone's final
             output, inside the same `GradientTape`, so gradients flow
             from the prediction back to the conv feature maps.
        """
        import tensorflow as tf

        try:
            backbone = None
            for layer in self._model.layers:
                if isinstance(layer, tf.keras.Model):
                    backbone = layer
                    break

            if backbone is None:
                logger.warning(
                    "No nested backbone sub-model found; skipping Grad-CAM."
                )
                return None

            try:
                last_conv_layer = backbone.get_layer(self._last_conv_layer_name)
            except ValueError:
                logger.warning(
                    "Grad-CAM target layer '%s' not found in backbone "
                    "'%s'; skipping heatmap.",
                    self._last_conv_layer_name,
                    backbone.name,
                )
                return None

            backbone_grad_model = tf.keras.models.Model(
                inputs=backbone.input,
                outputs=[last_conv_layer.output, backbone.output],
            )

            # Head layers applied after the backbone in build_model.py,
            # in the exact order they were constructed (a strictly linear
            # chain: GAP -> BN -> Dropout -> Dense -> BN -> Dropout ->
            # predictions). Replaying them manually lets gradients flow
            # from the final prediction back to the backbone's conv
            # feature maps despite the sub-model boundary.
            head_layers = [
                layer
                for layer in self._model.layers
                if layer is not backbone
                and not isinstance(layer, tf.keras.layers.InputLayer)
            ]

            image_tensor = tf.expand_dims(
                tf.convert_to_tensor(preprocessed_image, dtype=tf.float32), 0
            )

            with tf.GradientTape() as tape:
                conv_output, backbone_output = backbone_grad_model(image_tensor)
                tape.watch(conv_output)
                x = backbone_output
                for layer in head_layers:
                    x = layer(x, training=False)
                predictions = x
                loss = predictions[:, class_index]

            grads = tape.gradient(loss, conv_output)
            if grads is None:
                logger.warning(
                    "Grad-CAM gradient computation returned None; "
                    "skipping heatmap."
                )
                return None

            pooled_grads = tf.reduce_mean(grads, axis=(0, 1, 2))
            conv_output = conv_output[0]
            heatmap = conv_output @ pooled_grads[..., tf.newaxis]
            heatmap = tf.squeeze(heatmap)
            heatmap = tf.maximum(heatmap, 0) / (
                tf.math.reduce_max(heatmap) + 1e-8
            )
            heatmap = heatmap.numpy()

            heatmap = cv2.resize(
                heatmap,
                (preprocessed_image.shape[1], preprocessed_image.shape[0]),
            )
            heatmap_colored = cv2.applyColorMap(
                np.uint8(255 * heatmap), cv2.COLORMAP_JET
            )
            heatmap_colored = cv2.cvtColor(heatmap_colored, cv2.COLOR_BGR2RGB)

            base_image = np.uint8(preprocessed_image * 255)
            overlay = cv2.addWeighted(
                base_image, 0.6, heatmap_colored, 0.4, 0
            )

            success, buffer = cv2.imencode(
                ".png", cv2.cvtColor(overlay, cv2.COLOR_RGB2BGR)
            )
            if not success:
                return None
            return base64.b64encode(buffer).decode("utf-8")
        except Exception as exc:  # noqa: BLE001
            logger.error("Grad-CAM generation failed: %s", exc)
            return None

    # ------------------------------------------------------------------
    def predict(
        self, image_path: str, generate_gradcam: bool = True
    ) -> PredictionResult:
        """Run the full inference pipeline on a single uploaded image."""
        if not self.is_loaded and not self.load():
            return PredictionResult(
                predicted_class="",
                confidence=0.0,
                top_k=[],
                all_probabilities={},
                risk_level="Unknown",
                explanation="",
                inference_time_ms=0.0,
                model_version="",
                architecture="",
                timestamp=datetime.now(timezone.utc).isoformat(),
                errors=[
                    "No trained model is available yet. Train the model "
                    "first (see README: Training)."
                ],
            )

        start = time.perf_counter()

        result = preprocess_image(
            image_path,
            target_size=self.config.IMAGE_SIZE,
            apply_enhancement=True,
            normalize=True,
        )
        if not result.is_valid:
            return PredictionResult(
                predicted_class="",
                confidence=0.0,
                top_k=[],
                all_probabilities={},
                risk_level="Unknown",
                explanation="",
                inference_time_ms=0.0,
                model_version=self._version_info.get("app_version", ""),
                architecture=self._version_info.get("architecture", ""),
                timestamp=datetime.now(timezone.utc).isoformat(),
                errors=result.errors,
            )

        batch = np.expand_dims(result.image, axis=0)
        probabilities = self._model.predict(batch, verbose=0)[0]

        ranked = sorted(
            zip(self._class_names, probabilities),
            key=lambda pair: pair[1],
            reverse=True,
        )
        predicted_class, confidence = ranked[0]
        top_k = [
            {"class": name, "confidence": float(prob)}
            for name, prob in ranked[:3]
        ]
        all_probabilities = {
            name: float(prob) for name, prob in zip(self._class_names, probabilities)
        }

        gradcam_b64 = None
        if generate_gradcam:
            class_index = self._class_names.index(predicted_class)
            gradcam_b64 = self._generate_gradcam(result.image, class_index)

        elapsed_ms = (time.perf_counter() - start) * 1000
        risk_level = self._risk_level(predicted_class, float(confidence))

        return PredictionResult(
            predicted_class=predicted_class,
            confidence=float(confidence),
            top_k=top_k,
            all_probabilities=all_probabilities,
            risk_level=risk_level,
            explanation=self._explanation(predicted_class, risk_level),
            inference_time_ms=round(elapsed_ms, 2),
            model_version=self._version_info.get("app_version", self.config.APP_VERSION),
            architecture=self._version_info.get("architecture", self.config.MODEL_ARCHITECTURE),
            timestamp=datetime.now(timezone.utc).isoformat(),
            gradcam_base64=gradcam_b64,
        )
